Show signtool output on error
Squirrel/Squirrel.Windows pull request #1799
Opened 2022-04-13 17:01 UTC by mjerde

The signtool output is captured but only displayed in the event of success. This makes it hard to identify the causes of signtool problems, especially since signtool is operating on files in a temp location which are cleaned up after failure. Adding output of the signtool output on error helped me identify the cause of a problem I had when trying to releasify.

Thank you, Squirrel team!

2022-04-13 18:48 UTC, caesay commented
This has been fixed (along with several other signing related issues) [in my fork here](https://github.com/clowd/Clowd.Squirrel).

2022-04-16 13:17 UTC, robmen requested changes

2022-04-16 13:17 UTC, robmen commented on src/Update/Program.cs
> +                Console.WriteLine(processResult.Item2);
Instead of writing to the Console how about adding the output to the exception message instead?

2022-04-17 20:54 UTC, anaisbetts commented on src/Update/Program.cs
> +                Console.WriteLine(processResult.Item2);
👍

2022-04-17 20:55 UTC, anaisbetts commented on src/Update/Program.cs
> +                Console.WriteLine(processResult.Item2);
My only question is, are we sure that signtool output never leaks secrets?

2022-04-17 21:08 UTC, robmen commented on src/Update/Program.cs
> +                Console.WriteLine(processResult.Item2);
All good. It does not.

2022-04-20 21:08 UTC, mjerde commented on src/Update/Program.cs
> +                Console.WriteLine(processResult.Item2);
Since line 602 is already identical to this line, called in the non-error case, I would say this (writing to Console) is consistent with the program as it is already.

My only concern with adding it to the exception is that it would lend itself to making the error difficult to read as the exception text gets larger. Being some years since I was a daily C# dev, I don't presently have the expertise to identify the full range of possible effects for a large exceptions text but feel comfortable assessing that captured STDOUT will retain readability when written to Console.

2022-10-10 14:54 UTC, RADOVSHOP commented on src/Update/Program.cs
> +                Console.WriteLine(processResult.Item2);
- - [ ] @~~~~

2023-02-03 19:17 UTC, mjerde commented
Closed due to lack of traction.

2023-02-03 19:17 UTC, closed without merging