Fix app can not restart after an unexpected exit during the apply releases
Squirrel/Squirrel.Windows pull request #1862
Opened 2023-07-28 06:33 UTC by q837477816

Use a temp directory to apply for the releases and then rename the temp directory to the final release directory

2023-07-28 17:01 UTC, anaisbetts commented
While this isn't the worst idea on its face, unfortunately solutions like this will cause 3rd party Antivirus to flag because you are moving executables out of a temp directory (generally the more you move an executable once it is written out, the more you are going to trigger them). 

You should not quit the app while updates are running - when the user selects Quit, don't kill the process, just close the window, await the update to finish, then quit

2023-07-28 17:03 UTC, anaisbetts commented
Instead of doing this, write a `.not-finished` file in the app folder, and delete it when it's finished. Then, make the stubs ignore folders with `.not-finished` and delete any folders on update check that _do_ have `.not-finished`

Also, don't quit your application while updates are running - instead of exiting, hide the window, await the update, then close once it finishes

2023-07-29 09:52 UTC, q837477816 commented
> Instead of doing this, write a `.not-finished` file in the app folder, and delete it when the update successfully completes. Then, make the stubs ignore folders with `.not-finished` and delete any folders on update check that _do_ have `.not-finished`. This seems more complicated but it avoids moving executables around or renaming folders, which often triggers 3rd party antivirus

Agreed, I have submitted another commit, plz help review it, thanks. About `delete any folders on update check that do have .not-finished`, I don't need to add extra logic to handle this part since it already covers in https://github.com/Squirrel/Squirrel.Windows/blob/0ee9447d0f70744ad3624de953fc0eccf600990a/src/Squirrel/UpdateManager.ApplyReleases.cs#L306
and
https://github.com/Squirrel/Squirrel.Windows/blob/0ee9447d0f70744ad3624de953fc0eccf600990a/src/Squirrel/UpdateManager.ApplyReleases.cs#L96


> Also, don't quit your application while updates are running - instead of exiting, hide the window, await the update, then close once it finishes

Yes, during the upgrade process, we don't recommend users to exit the app. But we can't guarantee whether the app will be exited due to other reasons, such as crash or system shutdown. So we need this part logic to make sure users won't be able to launch the app due to the uncompleted upgrade.

2023-07-29 19:37 UTC, anaisbetts requested changes
A few small things but this looks good

2023-07-29 19:37 UTC, anaisbetts commented on src/Squirrel/UpdateManager.ApplyReleases.cs
> +                    if (File.Exists(notFinishedFilePath)) {
As a general programming rule, don't `stat` / `Exists` before doing a filesystem operation because it's a race condition, just Do It and deal with the failure

2023-07-29 19:37 UTC, anaisbetts commented on src/StubExecutable/StubExecutable.cpp
> +        if (FileExists(dirPath + L"\\.not-finished")) {
Indentation is weird?

2023-07-30 03:37 UTC, q837477816 commented on src/Squirrel/UpdateManager.ApplyReleases.cs
> +                    if (File.Exists(notFinishedFilePath)) {
fixed

2023-07-30 03:37 UTC, q837477816 commented on src/StubExecutable/StubExecutable.cpp
> +        if (FileExists(dirPath + L"\\.not-finished")) {
fixed

2023-08-01 02:47 UTC, q837477816 commented
> A few small things but this looks good

Hi @anaisbetts , plz review it again, thx

2023-08-01 17:34 UTC, anaisbetts approved these changes

2023-08-01 17:34 UTC, merged

2023-11-04 14:23 UTC, caesay commented
Not sure if I missed something here, but I don't think this covers the `Update.exe --processStart` case, which will seemingly still launch the broken directory.

2023-12-22 13:07 UTC, damonyu666 commented
@caesay In fact, when launching the app through "Update.exe --processStart," it initiates the latest version recorded in the local RELEASES file. However, if the last upgrade attempt failed, the RELEASES file remains unchanged, and as a result, it won't launch the broken directory.